### ISSUE TITLE
Making the scripts useful in the PDF format

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#174]
We are struggling to construct useful PDF.

(Since we are struggling, it is not to be expected that users would succeed printing HTML in a useful manner. So we really need to solve this problem for the user by providing good PDF.)

I tried Safari und Chrome.

They both produce (upon Print, Save to PDF) PDF like this:

![image](https://cloud.githubusercontent.com/assets/1208815/25629023/6c419b36-2f68-11e7-93cc-3b0e75eb4fa6.png)

That is, there is loads of links included verbatim, which makes it hard to even read the text.

I tried https://www.printfriendly.com

Then I am getting another problem:

![image](https://cloud.githubusercontent.com/assets/1208815/25629055/8992db64-2f68-11e7-81a8-4a7430f8b437.png)

That is, while the content looks good overall, all kinds of hidden links for UI actions such as saving and deletion are discovered.

The latter problem could be probably solved by suppressing some elements in the HTML of the generated script page.

Any other ideas?

**Comment by rlaemmel** [comment]
cc @MarcelH91

**Comment by rlaemmel** [comment]
I am starting to think that the simplest solution is maybe to really remove all links or to have an option at least when generating the script because in this way one gets something useful with the print function of the browser.

**Comment by MarcelH91** [comment]
Yup, otherwise I could think of funny functionality like creating PDF versions ourselves. This is a bigger problem, since you could really try to think in general about how to make use of linked data for teaching purposes.
The script could also include snippets retrieved from Wikipedia, if a term's definiton relies on it. E.g., Build Tool is not clear without more text when you just want to read the script and not access linked data deployed online.

For now, simply not printing links is probably the best. 
![i10 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/8490924/25662398/a1370a7c-3014-11e7-8712-3284d9d01a12.jpg)

**Comment by kevin-klein** [comment]
there is a "pdf" button now to generate pdf directly

**Comment by MarcelH91** [comment]
Looks good :-)
