### ISSUE TITLE
file markup rendering broken

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#184]
cc @MarcelH91 

I am here:

https://101wiki.softlang.org/Stack

I am seeing strange things like this:

![image](https://cloud.githubusercontent.com/assets/1208815/26316482/af4dc70e-3f14-11e7-9c61-5893d3b399dd.png)

**Comment by kevin-klein** [comment]
using <file> in a bullet list breaks markup rendering. it is caused by the way wikicloth (ruby gem for wikipedia markup language parsing) works and there is no easy fix for it, if this is an ongoing issue, i might come up with some solution which will probably be replacing the wikicloth parser with something else.

**Comment by kevin-klein** [comment]
if i read the [wikimarkup spec](https://www.mediawiki.org/wiki/Markup_spec/EBNF) correctly, there should only be regular text inside a unordered list element. the code is really hard to understand but i think it renders the markup stuff and takes the first html element in the tree which contains text and puts it into the list element and appends the rest after the list which is consistent with the output we see.

**Comment by rlaemmel** [comment]
I assume that the problematic markup was rendering fine in some previous version. I am totally Ok, with not allowing certain markup patterns. I have now also revised the content of the problematic page a bit more. I guess just use subsections instead of bullet lists.
