### ISSUE TITLE
Helpless at the Sparql prompt

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#217]
I know SPARQL, but I don't know what to enter.

![image](https://user-images.githubusercontent.com/1208815/28167630-7fdf4178-67dc-11e7-8e50-4429044fdcac.png)

The trouble is that I would probably need some prefixes and all this. 
So some prefilled query should be there and the right prefixes.

**Comment by kevin-klein** [comment]
i show the page https://101wiki.softlang.org/Language:sparql above the prompt. I planed for it to contain some 101wiki related content.

**Comment by MarcelH91** [comment]
Oh well, can you please add some pretty printing for the results?

Here is some example query:

SELECT ?x ?y 
WHERE {
  ?x <http://101companies.org/resources/uses> ?y .
}

The prefixes still have to be mentioned that are used in the store.
E.g., http://101companies.org/resources/.

**Comment by MarcelH91** [comment]
Besides, I wondered whether this only returns a restricted number of results.

With the query `SELECT ?x ?y ?z WHERE { ?x ?y ?z .}` I tried to explore the store. But I can't even find 'ANTLR'.

**Comment by kevin-klein** [comment]
this is caused by the pagination, it only show 100 items per result page, you can query multiple pages by using the page parameter:
https://101wiki.softlang.org/resources/query?utf8=%E2%9C%93&page=5&query=+SELECT+%3Fx+%3Fy+WHERE+{+%3Fx+%3Chttp%3A%2F%2F101companies.org%2Fresources%2Fuses%3E+%3Fy+.+}&commit=execute
