### ISSUE TITLE
Prefix gone missing (again)

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#83]
http://101companies.org/wiki/Script:Generic_functions

http://101companies.org/wiki/Script:Generic_functions

The backlink *without* prefix does indeed lead to a page that appears to be a copy of the page with prefix.

**Comment by rlaemmel** [comment]
This is a long-standing problems that seems to be coming back time and again.
Each time I run a search on something with a prefix I also seem to get the page without prefix.
For instance, I was just looking for "Flat" company -- the feature.
I am also getting something without prefix:

http://101companies.org/wiki/Flat_company

Please try to solve this problem.

**Comment by kevin-klein** [comment]
Actually it is a lot worse than we thought:
http://101companies.org/search?q=project
Some other pages have the same issue (http://101companies.org/search?q=email). I tried every possible action like renaming, creating pages, updating etc and i don't think it is caused by this (maybe it was at some point in time). Can you think of something, else i will delete everything but the newest version (after creating a backup)?

**Comment by kevin-klein** [comment]
I think it is fixed for now.
