### ISSUE TITLE
Improve search function to allow for search of members of namespaces

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#84]
We used to have "instanceOf" relationships to inject member pages into namespaces.
This would allow us to find members in the wiki.
These properties are no longer semantically valid.

Thus, we need another effective way to find all members of a namespace.
The search function could help here.

Suppose I want to see a list of "all languages".
Then I should be able to fire off a query like this "Language:*" or something else you see fit.

**Comment by rlaemmel** [comment]
I just realize that I can achieve more or less what I want by using this search string:

"Language:"

Perhaps, "*" and regexps could just be supported in some cheap way.

Of course, we could also document how to use the search function, but who reads documentation :-)

**Comment by kevin-klein** [comment]
At the moment, the wiki uses the mongoid_search gem which performs some kind of tokenization and runs some regex on the keyword list cached in the model. You will notice that you can not search for special characters (look here: https://github.com/mauriciozaffari/mongoid_search/blob/master/lib/mongoid_search/util.rb#L39). So "Language" produces the same results, as it turns out those regex matches over a list strings for a list of pages shows very poor performance due to the lack of full text index but can be patched to allow more features but we might also switch to some more mature system like SOLR or ElasticSearch which might be more beneficial on the long run on top of vastly superior performance.
