### ISSUE TITLE
auto break long lines in 101wiki editor

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#85]
When paragraphs are long, i.e., without line breaks, then they look weird in the editor.

See this example.

![image](https://cloud.githubusercontent.com/assets/1208815/9212739/e9e91cee-408b-11e5-8dc9-c3021ab8c287.png)

Only 1 line is shown and would need to scroll horizontally through the line.

What's needed is auto breaks when rendering the long line for edit.

(It used to be like this.)

**Comment by rlaemmel** [comment]
Even worse -- I cannot even reach the end of the line.
Changing this from "Clean up" to "Bug".

**Comment by rlaemmel** [comment]
When adding breaks manually, it looks good, but the point is that one should not be forced to add breaks manually.

**Comment by kevin-klein** [comment]
There should be a scroll bar at the bottom at least in my Browser.
![Contribution:seam](https://cloud.githubusercontent.com/assets/3279763/9212879/1bbbf498-408d-11e5-8dcd-eda9eff1654b.png)
Taken from this page: http://101companies.org/wiki/Contribution:seam/edit

It also auto scrolls for me as the cursor reachs the edge of the visible part. I suspect this is a browser problem? Which browser do you use and should i add auto line break instead of scrolling?
